# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := craig2kml

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

craig2kml: 
	@echo "==== Building craig2kml ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f craig2kml.make

clean:
	@${MAKE} --no-print-directory -C . -f craig2kml.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   craig2kml"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
